FROM mysql:5.5
MAINTAINER Daniel Jimenez Jerez <djimenez@agetic.gob.bo>

ENV MYSQL_DATABASE=nsiaf_production
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin
ENV MYSQL_ROOT_PASSWORD=root

VOLUME ["/var/lib/mysql"]
EXPOSE 3306
