require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SegurosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Seguro. As you add validations to Seguro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SegurosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all seguros as @seguros" do
      seguro = Seguro.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:seguros)).to eq([seguro])
    end
  end

  describe "GET #show" do
    it "assigns the requested seguro as @seguro" do
      seguro = Seguro.create! valid_attributes
      get :show, params: {id: seguro.to_param}, session: valid_session
      expect(assigns(:seguro)).to eq(seguro)
    end
  end

  describe "GET #new" do
    it "assigns a new seguro as @seguro" do
      get :new, params: {}, session: valid_session
      expect(assigns(:seguro)).to be_a_new(Seguro)
    end
  end

  describe "GET #edit" do
    it "assigns the requested seguro as @seguro" do
      seguro = Seguro.create! valid_attributes
      get :edit, params: {id: seguro.to_param}, session: valid_session
      expect(assigns(:seguro)).to eq(seguro)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Seguro" do
        expect {
          post :create, params: {seguro: valid_attributes}, session: valid_session
        }.to change(Seguro, :count).by(1)
      end

      it "assigns a newly created seguro as @seguro" do
        post :create, params: {seguro: valid_attributes}, session: valid_session
        expect(assigns(:seguro)).to be_a(Seguro)
        expect(assigns(:seguro)).to be_persisted
      end

      it "redirects to the created seguro" do
        post :create, params: {seguro: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Seguro.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved seguro as @seguro" do
        post :create, params: {seguro: invalid_attributes}, session: valid_session
        expect(assigns(:seguro)).to be_a_new(Seguro)
      end

      it "re-renders the 'new' template" do
        post :create, params: {seguro: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested seguro" do
        seguro = Seguro.create! valid_attributes
        put :update, params: {id: seguro.to_param, seguro: new_attributes}, session: valid_session
        seguro.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested seguro as @seguro" do
        seguro = Seguro.create! valid_attributes
        put :update, params: {id: seguro.to_param, seguro: valid_attributes}, session: valid_session
        expect(assigns(:seguro)).to eq(seguro)
      end

      it "redirects to the seguro" do
        seguro = Seguro.create! valid_attributes
        put :update, params: {id: seguro.to_param, seguro: valid_attributes}, session: valid_session
        expect(response).to redirect_to(seguro)
      end
    end

    context "with invalid params" do
      it "assigns the seguro as @seguro" do
        seguro = Seguro.create! valid_attributes
        put :update, params: {id: seguro.to_param, seguro: invalid_attributes}, session: valid_session
        expect(assigns(:seguro)).to eq(seguro)
      end

      it "re-renders the 'edit' template" do
        seguro = Seguro.create! valid_attributes
        put :update, params: {id: seguro.to_param, seguro: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested seguro" do
      seguro = Seguro.create! valid_attributes
      expect {
        delete :destroy, params: {id: seguro.to_param}, session: valid_session
      }.to change(Seguro, :count).by(-1)
    end

    it "redirects to the seguros list" do
      seguro = Seguro.create! valid_attributes
      delete :destroy, params: {id: seguro.to_param}, session: valid_session
      expect(response).to redirect_to(seguros_url)
    end
  end

end
